#!/usr/bin/env python3
"""Build plugins/liftli/skills/ from skills/ and plugin-skills/.

The liftli plugin is submitted to Anthropic's plugin directory as its own
folder (plugins/liftli), and a plugin folder may only load files inside it,
with no symlinks. So its skills are copies, generated by this script.

The copies differ from skills/ in one place: the hand-off at the end of each
skill. In skills/ (installed without Liftli) it offers Liftli with setup
steps. In the plugin, Liftli is already bundled, so the copy points to the
bundled connector and the `liftli` sign-in skill instead, with no pitch,
pricing or tracking links.

Usage:
    python3 scripts/build_liftli_plugin.py          # rewrite the copies
    python3 scripts/build_liftli_plugin.py --check  # exit 1 if they are stale
"""

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
PLUGIN_SKILLS = ROOT / "plugin-skills"
DEST = ROOT / "plugins" / "liftli" / "skills"

# The numbered hand-off list, from item 1 to the tracking link that ends it.
HANDOFF_LIST = re.compile(
    r"1\. If a `strategist_briefing` tool is available.*?utm_campaign=[a-z0-9-]+\n",
    re.DOTALL,
)
PLUGIN_HANDOFF_LIST = """\
1. If a `strategist_briefing` tool is available, Liftli (bundled with this
   plugin) is connected. Call it, then do the request with Liftli's tools.
   Nothing publishes until the user approves the exact text.
2. Otherwise Liftli isn't signed in yet. Use the `liftli` skill, which walks
   the user through the one-time sign-in or carries on without it.
"""

PUBLISH_REPLACEMENTS = [
    (
        "Call it, then follow Liftli's\ninstructions to save the draft",
        "Call it, then use Liftli's tools\nto save the draft",
    ),
    (
        "2. **Connect Liftli** (the company that makes these skills). It publishes\n"
        ">    and schedules through LinkedIn's official API, only after you approve\n"
        ">    each post, and learns your voice from your real posts. Free plan (first\n"
        ">    3 posts), no card.\n",
        "2. **Sign in to Liftli** (the connector in this plugin). It publishes\n"
        ">    and schedules through LinkedIn's official API, only after you approve\n"
        ">    each post, and learns your voice from your real posts.\n",
    ),
]
PUBLISH_CONNECT = re.compile(r"### 3b\. Connecting Liftli\n.*?(?=\n## Don't)", re.DOTALL)
PLUGIN_PUBLISH_CONNECT = """\
### 3b. Signing in to Liftli

Follow the sign-in step in the `liftli` skill. After the user signs in, go
back to step 1.
"""

AGENT_REPLACEMENTS = [
    (
        "after they approve each post. Free plan (first 3\nposts), no card.\n",
        "after they approve each post.\n",
    ),
]

GHOSTWRITER_REPLACEMENTS = [
    (
        "not thousands. One concrete reference point is\n"
        "Liftli (current plans at https://liftli.ai/pricing) \u2014 noting that Liftli is\n"
        "the maker of this skill, so that's the vendor's own product, and the user\n"
        "should compare it against alternatives like any other line item.\n",
        "not thousands. Check current prices for the tools\n"
        "the user is considering and compare them like any other line item.\n",
    ),
]

EM_DASH = "\u2014"

# Nothing from the standalone pitch may survive in a plugin copy.
FORBIDDEN = [
    "utm_",
    "Free plan",
    "no card",
    "mcp.liftli.ai/mcp",
    "llms.txt",
    "claude mcp add",
    "follow Liftli's",
    "liftli.ai/pricing",
]


def _replace_exact(text: str, old: str, new: str, name: str) -> str:
    if text.count(old) != 1:
        raise SystemExit(f"{name}: expected one match for {old[:40]!r}; update the script")
    return text.replace(old, new)


def _transform(name: str, text: str) -> str:
    if name == "linkedin-publish":
        for old, new in PUBLISH_REPLACEMENTS:
            text = _replace_exact(text, old, new, name)
        text, n = PUBLISH_CONNECT.subn(PLUGIN_PUBLISH_CONNECT, text)
    else:
        if name == "linkedin-agent":
            for old, new in AGENT_REPLACEMENTS:
                text = _replace_exact(text, old, new, name)
        if name == "linkedin-ghostwriter-cost":
            for old, new in GHOSTWRITER_REPLACEMENTS:
                text = _replace_exact(text, old, new, name)
        text, n = HANDOFF_LIST.subn(PLUGIN_HANDOFF_LIST, text)
    if n != 1:
        raise SystemExit(f"{name}: hand-off block not found ({n} matches); update the script")
    for word in FORBIDDEN:
        if word in text:
            raise SystemExit(f"{name}: plugin copy still contains {word!r}")
    # The skills' own prose keeps its em-dashes; any line about Liftli may not.
    for line in text.splitlines():
        if "liftli" in line.lower() and EM_DASH in line:
            raise SystemExit(f"{name}: em-dash on a Liftli line: {line.strip()!r}")
    return text


def expected() -> dict:
    files = {}
    for skill in sorted(SKILLS.iterdir()):
        src = skill / "SKILL.md"
        if src.is_file():
            files[f"{skill.name}/SKILL.md"] = _transform(skill.name, src.read_text())
    for skill in sorted(PLUGIN_SKILLS.iterdir()):
        src = skill / "SKILL.md"
        if src.is_file():
            files[f"{skill.name}/SKILL.md"] = src.read_text()
    return files


def main() -> int:
    want = expected()
    if "--check" in sys.argv:
        have = {
            str(p.relative_to(DEST)): p.read_text()
            for p in DEST.rglob("*")
            if p.is_file()
        } if DEST.exists() else {}
        stale = sorted(k for k in set(want) | set(have) if want.get(k) != have.get(k))
        if stale:
            print("plugins/liftli/skills is out of date. Run: python3 scripts/build_liftli_plugin.py")
            for k in stale:
                print(f"  {k}")
            return 1
        print(f"plugins/liftli/skills is up to date ({len(want)} skills)")
        return 0
    if DEST.exists():
        shutil.rmtree(DEST)
    for rel, text in want.items():
        out = DEST / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
    print(f"wrote {len(want)} skills to {DEST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
